# Generated by Django 5.0.2 on 2024-02-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0006_commentcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentComment',
        ),
    ]
